make JamtisDestinationV1 serializable
UkoeHB/monero pull request #11
Opened 2023-06-06 19:11 UTC by DangerousFreedom1984

Could you please add these changes? I need to work with a serialized JamtisDestinationV1.

2023-06-06 21:53 UTC, UkoeHB requested changes

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_types.h
> +BLOB_SERIALIZER(sp::jamtis::address_tag_t);
This needs a `ser_address_tag_t`

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +    serializable_dest_out.addr_tag = dest.addr_tag;
```suggestion
    serializable_dest_out.addr_K1  = dest.addr_K1;
    serializable_dest_out.addr_K2  = dest.addr_K2;
    serializable_dest_out.addr_K3  = dest.addr_K3;
    serializable_dest_out.addr_tag = dest.addr_tag;
```
Alignment

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +    dest_out.addr_tag = serializable_destination.addr_tag;
```suggestion
    dest_out.addr_K1  = serializable_destination.addr_K1;
    dest_out.addr_K2  = serializable_destination.addr_K2;
    dest_out.addr_K3  = serializable_destination.addr_K3;
    dest_out.addr_tag = serializable_destination.addr_tag;
```

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.cpp
> +#include "crypto/chacha.h"
Why is this here?

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
> +BLOB_SERIALIZER(crypto::x25519_secret_key);
```suggestion
BLOB_SERIALIZER(crypto::x25519_secret_key);

```
Files needs a newline at the bottom.

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
>  };
```suggestion
    END_SERIALIZE()
};
```

Please clean up whitespace issues like this before making a PR.

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
> +    crypto::chacha_iv m_encryption_iv;
I would prefer that you implement a password-protected wrapper class instead of embedding encryption details inside the struct.

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
> +    END_SERIALIZE()
The entire struct does not need to be serializable. You can recover the other keys from `k_m` and `k_vb`. I recommend adding mock_serializable/etc. files to the seraphis_mocks directory, mimicking the seraphis_impl serialization files. Then you can easily recover all the non-core keys during deserialization.

2023-06-06 21:53 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.h
> +void recover_sp_destination_v1(const ser_JamtisDestinationV1 &serializable_destination, jamtis::JamtisDestinationV1 &dest_out);
A) why whitespace?
B) why is destination ordered between coinbase and squashted tx types? It is not consistent with the make_serializable section.

2023-06-06 21:54 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
> +BLOB_SERIALIZER(crypto::x25519_secret_key);
Also, it is not appropriate to have `BLOB_SERIALIZER(crypto::x25519_secret_key);` here. If it should be anywhere, it should be in `src/serialization/crypto.h`.

2023-06-06 22:17 UTC, UkoeHB commented on src/seraphis_mocks/jamtis_mock_keys.h
> +    crypto::chacha_iv m_encryption_iv;
I think you could write a template for password-protected keys.
A) static assert that the template type is POD
B) encrypt/decrypt the entire data struct as raw data (cast to void* and encrypt/decrypt in-place)
C) use RAII somehow to ensure the struct is re-encrypted as needed
D) be sure to safely handle multithreaded access to the protected container

2023-06-07 06:21 UTC, DangerousFreedom1984 commented on src/seraphis_impl/serialization_demo_utils.cpp
> +    dest_out.addr_tag = serializable_destination.addr_tag;
Ok

2023-06-07 07:22 UTC, DangerousFreedom1984 commented
Thanks for the detailed comments.

I will let ghostway make the changes (if he did not do it yet) related to the key_container (jamtis_mock_keys.*) as he is working on it. So I removed this part from the PR.

2023-06-07 18:36 UTC, UkoeHB requested changes

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_types.h
> +
This should be ordered above the encrypted address tag.

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_types.h
> +struct ser_JamtisDestinationV1 final
Again, ordering

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_types.h
> +BLOB_SERIALIZER(sp::serialization::ser_address_tag_t);
And again, ordering

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +#include "seraphis_core/jamtis_destination.h"
Alphabetize

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +void make_serializable_sp_destination_v1(const jamtis::JamtisDestinationV1 &dest, ser_JamtisDestinationV1 &serializable_dest_out)
Ordering

2023-06-07 18:36 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +void recover_sp_destination_v1(const ser_JamtisDestinationV1 &serializable_destination, jamtis::JamtisDestinationV1 &dest_out)
Ordering

2023-06-07 19:07 UTC, DangerousFreedom1984 commented on src/seraphis_impl/serialization_demo_types.h
> +struct ser_JamtisDestinationV1 final
I did not get the logic of the order for the structs here so I put in the end

2023-06-07 21:42 UTC, UkoeHB requested changes

2023-06-07 21:42 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +    serializable_dest_out.addr_K3  = dest.addr_K3;
```suggestion
    serializable_dest_out.addr_K1 = dest.addr_K1;
    serializable_dest_out.addr_K2 = dest.addr_K2;
    serializable_dest_out.addr_K3 = dest.addr_K3;
```

2023-06-07 21:42 UTC, UkoeHB commented on src/seraphis_impl/serialization_demo_utils.cpp
> +    dest_out.addr_K3  = serializable_destination.addr_K3;
```suggestion
    dest_out.addr_K1 = serializable_destination.addr_K1;
    dest_out.addr_K2 = serializable_destination.addr_K2;
    dest_out.addr_K3 = serializable_destination.addr_K3;
```

2023-06-08 23:34 UTC, UkoeHB approved these changes

2023-06-08 23:35 UTC, merged