jamtis: implement find-received privacy changes [WIP]
UkoeHB/monero pull request #15
Opened 2023-09-06 02:43 UTC by jeffro256

Description of changes can be found here: https://gist.github.com/tevador/50160d160d24cfc6c52ae02eb3d17024?permalink_comment_id=4665372#gistcomment-4665372

2023-09-06 21:11 UTC, UkoeHB requested changes
Just skimmed it for now. I recommend running comparative perf tests for scanning before/after this PR and adding them to the PR comments.

2023-09-06 21:11 UTC, UkoeHB commented on tests/performance_tests/view_scan.h
> +            } while(svt_temp != sp::sparse_view_tag(m_basic_records.back().enote));
This does not look right, I think you broke this test.

2023-09-06 21:17 UTC, jeffro256 commented on tests/performance_tests/view_scan.h
> +            } while(svt_temp != sp::sparse_view_tag(m_basic_records.back().enote));
You're right about that...

2023-09-06 22:00 UTC, jeffro256 commented
Here's the results of `test_remote_scanner_client_scan_sp` performance test after fixing it:
```
seraphis_lib (original) run #1
test_remote_scanner_client_scan_sp (23 calls) - OK: 13434 µs/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 13217 µs/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 14304 µs/call

seraphis_lib (original) run #2
test_remote_scanner_client_scan_sp (23 calls) - OK: 13086 µs/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 13130 µs/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 14217 µs/call

jamtis_fix_fr_privacy (new PR) run #1
test_remote_scanner_client_scan_sp (23 calls) - OK: 1738 ms/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 1738 ms/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 1739 ms/call

jamtis_fix_fr_privacy (new PR) run #2
test_remote_scanner_client_scan_sp (23 calls) - OK: 1731 ms/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 1750 ms/call
test_remote_scanner_client_scan_sp (23 calls) - OK: 1734 ms/call
```

Ran on an AMD Ryzen 9 3900X 12-core CPU. So processing basic records from a remote scanner is ~128x slower (about what was predicted from Tevador's cycle estimates).

2023-09-07 01:53 UTC, jeffro256 commented
One performance difference that works in the new changes favor, though, is that basic records are 9% smaller because the nominal address index is not transmitted.

2023-09-10 22:47 UTC, UkoeHB commented
If my math is right, the updated scanning for a scanner client is 1s per 10mill on-chain enotes (40k are scanned locally). 40k enotes transmitted for local scanning is at least 5-10MB so the overall cost is comparable with modern download speeds.

2023-12-03 16:46 UTC, jeffro256 commented
Closing in favor of #26

2023-12-03 16:46 UTC, closed without merging