derive view_balance from master key
UkoeHB/monero pull request #29
Opened 2024-02-17 10:27 UTC by DangerousFreedom1984

Add view_balance derivation from master key as specified by [KeyDerive1](https://gist.github.com/tevador/50160d160d24cfc6c52ae02eb3d17024#331-curve25519) in the Jamtis spec.

2024-02-17 19:05 UTC, UkoeHB commented on src/seraphis_core/jamtis_core_utils.cpp
> +    sp_derive_x25519_key(to_bytes(k_master), transcript.data(), transcript.size(), k_view_balance_out.data);
`k_vb` is not an X25519 key.

2024-02-18 00:58 UTC, DangerousFreedom1984 commented on src/seraphis_core/jamtis_core_utils.cpp
> +    sp_derive_x25519_key(to_bytes(k_master), transcript.data(), transcript.size(), k_view_balance_out.data);
Right. I was confused with the notation though it was clearly a crypto::secret_key. Sorry.
So the only requirement here is a scalar that is reduced? (from my experience with Ed25519 looks so).
Do we also need to clamp (clear the cofactor setting some bits to 0) ? Would that bring some useful parity with the X25519 keys?
Do the inversion operations require other constraints on these private keys?

2024-02-22 04:30 UTC, UkoeHB requested changes

2024-02-22 04:30 UTC, UkoeHB commented on src/seraphis_core/jamtis_core_utils.cpp
> +    // k_vb = H_64[k_m]() mod l
```suggestion
    // k_vb = H_n[k_m]()
```

2024-02-22 04:30 UTC, UkoeHB commented on src/seraphis_core/jamtis_core_utils.h
> +*/
```suggestion
/**
* brief: make_jamtis_viewbalance_key - view-balance key, for viewing all balance information
*   k_vb = H_n[k_m]()
* param: k_master - k_m
* outparam: k_view_balance_out - k_vb
*/
```

2024-02-22 09:14 UTC, DangerousFreedom1984 reviewed
Thanks. Just a few questions (not really related to private keys but scalars).
1) What are the requirements for the scalars in Ed25519 ?
They need just to be in range ]0..L[ (where L = 2^252 + 27742317777372353535851937790883648493) ?

2) According to [that](https://doc.libsodium.org/advanced/point-arithmetic#scalar-multiplication-without-clamping), if we clamp scalars (as done for X25519) we may have troubles to invert them. Do you know an example of that or why this is so?

3) Since we can't clamp scalars apparently due to the fact that they need to be invertible (for key image proofs for example), this means that we would always be susceptible to the small groups attacks? Does it even make sense to talk about that since we dont care about points in general except for the key_image?

2024-02-22 18:24 UTC, UkoeHB commented
> What are the requirements for the scalars in Ed25519 ?

Yes, we always call `sc_check()` on scalars in proof verification.

> According to [that](https://doc.libsodium.org/advanced/point-arithmetic#scalar-multiplication-without-clamping), if we clamp scalars (as done for X25519) we may have troubles to invert them. Do you know an example of that or why this is so?

The link is referring to ed25519 where we do not clear the lower bits of scalars. If you mutate the scalar, then the inverse of that scalar times the mutated scalar will not equal 1.

> Since we can't clamp scalars apparently due to the fact that they need to be invertible (for key image proofs for example)

We do not clamp scalars because the original crypto library from Bernstein does not clamp scalars. Clamping would get in the way of all our cryptography where we want the mul8s to be explicit.

>  this means that we would always be susceptible to the small groups attacks?

We mul8 where necessary.

> Does it even make sense to talk about that since we dont care about points in general except for the key_image?

Small group attacks are related to public keys, not scalars. Clamping is just 'forcing' mul8, which we do manually where necessary.

2024-02-22 18:24 UTC, merged