seraphis_crypto: split BulletproofPlus2 into proof-only and complete structs
UkoeHB/monero pull request #31
Opened 2024-02-21 04:58 UTC by jeffro256

In `SpTxSquashedV1`, we have commitments (sp enote image and output), and we have a balance proof. However, the commitments were stored doubly, inside the in/out lists, and inside the proof. This PR splits up the Bulletproof into two parts: the values we are committing to/verifying, and the proof itself. Now inside the `SpBalanceProofV1`, we store just the proof, and not the committed values. Doing this has many positive effects for code quality. First, it is now immediately clear to a new reader that the balance proof won't hold commitments; they "belong" to either an enote image or an output. Secondly, downstream developers cannot set bulletproof commitments points, so they can't screw up the 1/8 multiply. Thirdly, this setup makes the transaction format more "rigid": there are fewer fields that conflict with each other and there is less room for making silly mistakes based on assumptions that all fields are important and will change outputs of functions. For a real world example of what I mean, look at PR fix https://github.com/monero-project/monero/pull/8707. There was a cache coded for RingCT signatures with the assumption that changing certain fields of the RingCT signatures would lead to a different serialization, and thus changing fields would invalidate the cache. This was NOT the case, and the cache would have added in an inflation bug if not for a technicality in the way that RingCT signatures were deserialized and "expanded" using different elements of the `cryptonote::transaction` class. If `cryptonote::transaction` perhaps had a more rigid way of constructing the signatures, it wouldn't have been a problem in the first place. This is the main goal of this PR: minimize potential future risky behavior.

One thing that needs to be double-checked in this PR is that all commitments are bound to in some part of the TXID. 

Depends on #30

2024-02-21 21:10 UTC, UkoeHB commented
I originally made the minimum number of changes to BP+ compared to master in order to avoid review headaches.

2024-02-21 22:55 UTC, jeffro256 commented
The actual changes to src/seraphis_crypto/bulletproofs2* is pretty trivial IMO. It just gets split into 2 structs

2024-02-22 05:35 UTC, UkoeHB requested changes
The main problem here is re-validating the same transaction is more expensive. You have to allocate the V pointer vec, and you need to *1/8 all the points. Doesn't the mempool do tx revalidation after deserializing?

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/bulletproofs_plus2.cpp
> +        const std::vector<const BulletproofPlus2Proof*> &proofs,
```suggestion
    bool try_get_bulletproof_plus2_verification_data(const std::vector<const rct::keyV*> &Vs,
        const std::vector<const BulletproofPlus2Proof*> &proofs,
```

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/bulletproofs_plus2.h
> +    rct::keyV V; //! @brief Pederson commitment points
```suggestion
    rct::keyV V; //! @brief Pederson commitment points multiplied by (1/8)
```

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/bulletproofs_plus2.h
> +    const std::vector<const BulletproofPlus2Proof*> &proofs,
```suggestion
bool try_get_bulletproof_plus2_verification_data(const std::vector<const rct::keyV*> &Vs,
    const std::vector<const BulletproofPlus2Proof*> &proofs,
```

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +std::size_t bpp_size_bytes_lr(const std::size_t lr_length)
This function should be ordered above `bpp_size_bytes`.

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +std::size_t bpp_weight_lr(const std::size_t lr_length)
Same here, order above `bpp_weight()`.

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +    CHECK_AND_ASSERT_THROW_MES(lr_length >= 6, "L/R length can not less than 6: " << lr_length);
```suggestion
    CHECK_AND_ASSERT_THROW_MES(lr_length >= 6, "L/R length can not be less than 6: " << lr_length);
```

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +    const std::size_t num_two_agg_groups = (1 << (lr_length - 6)) >> 1;
Shouldn't this be `2^(LR-length - 6) / 2` = `2^(LR-length - 7)`?

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_main/txtype_squashed_v1.cpp
> +            num_range_proofs))
This is now redundant, check the implementation of `validate_sp_semantics_component_counts_v1()`.

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_main/txtype_squashed_v1.cpp
> +        rct::keyV &curr_tx_commitments = tools::add_element(tx_commitments);
Interesting to see a new use for this in the wild.

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_main/txtype_squashed_v1.cpp
> +        // gather enote images and also their masked commitments (mult 1/8)
```suggestion
        // gather enote images and also their masked commitments (mul 1/8)
```

2024-02-22 05:35 UTC, UkoeHB commented on src/seraphis_main/txtype_squashed_v1.cpp
> +                rct::INV_EIGHT));
```suggestion
        // make keyV for all output commitments (mul 1/8)
        for (const SpEnoteV1 &sp_output_enote : tx->outputs)
        {
            curr_tx_commitments.push_back(rct::scalarmultKey(sp_output_enote.core.amount_commitment,
                rct::INV_EIGHT));
        }
```
Braces if your block-scope is multiple lines.

2024-02-22 19:29 UTC, jeffro256 commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +    const std::size_t num_two_agg_groups = (1 << (lr_length - 6)) >> 1;
I also have the `>> 1` at the end which divides it by 2 rounding down. `(1 << (lr_length - 6)) >> 1` is equal to `2^(LR-length - 7)` *except* when `lr_length` is equal to 6, then the latter will overflow.

2024-02-22 19:39 UTC, jeffro256 commented
Regarding your main comment, we have to multiply either by 1/8 or 8 anyways even if we store `V` inside the balance proof, since if we don't do that, we open ourselves up to inflation bugs where the transaction author proves the range of values inside `V`, but those are different to what the inputs/outputs commitments are. Also, with the current serialization demo utils, this was being done anyways. So the only performance difference here is that we do have to copy the `V` vector. I haven't tested this, so take this with a grain of salt, but I suspect that the speed of copying ~128 commitment bytes in `V` (for a 2/2 tx) will be absolutely dwarfed by the time of the actual EC operations required to verify the BP+.

2024-02-22 19:59 UTC, jeffro256 commented on src/seraphis_main/txtype_squashed_v1.cpp
> +            num_range_proofs))
Good catch

2024-02-22 21:45 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.cpp
> +    const std::size_t num_two_agg_groups = (1 << (lr_length - 6)) >> 1;
Ok yeah I realized your code works last night. I was confused about that right shift but now I get it.

2024-02-22 21:52 UTC, UkoeHB commented
> Regarding your main comment, we have to multiply either by 1/8 or 8 anyways even if we store V inside the balance proof to verify they match the inputs/outputs, since if we don't do that, we open ourselves up to inflation bugs where the transaction author proves the range of values inside V, but those are different to what the inputs/outputs commitments are.

Multiplying by 8 is way cheaper than multiplying by 1/8, that's why the 1/8 is outside the proof itself.

> Also, with the current serialization demo utils, this was being done anyways.

Yes, mul 1/8 when you deserialize. And then the deserialized struct can be re-validated multiple times without redundantly doing the mul 1/8.

> I haven't tested this, so take this with a grain of salt, but I suspect that the speed of copying ~128 commitment bytes in V (for a 2/2 tx) will be absolutely dwarfed by the time of the actual EC operations required to verify the BP+.

You'd be surprised. I shaved off like 5% from the unit test suite during my final library review mainly from reducing allocations by adding missing `.reserve()`s.

2024-02-26 19:12 UTC, jeffro256 commented
Okay after thinking about it for a while, I think we should design the transaction format so that the following actions are possible to perform without doing any multiplications by 8 or 1/8 on ED25519 points, even if we don't implement it in this library at this moment:
* Deserializing and then preparing points for verification [faster recent sync]
* Deserializing and then calculating the TXID [we want txs to be identified as quickly as possible so they can be categorized as seen, already verified, belonging to a checkpoint zone, etc]
* Deserializing and then performing a primary/auxiliary view tag check [even multiplying by 8 would slow down CPU time on syncing by about 50%]

Assuming that we won't have to multiply onetime addresses by 1/8 for grootle membership proofs, all we would have to do to implement these properties in the current Seraphis library with the fewest changes possible is:
* Serialize enote image and output commitments in their 1/8 form
* Add enote image and output commitments to the TXID transcript in their 1/8 form

Is this a good path forward?

2024-02-26 19:27 UTC, UkoeHB commented
I will think about this.

> Serialize enote image and output commitments in their 1/8 form

Is the idea to then mul8 on deserialization?

2024-02-26 19:33 UTC, jeffro256 commented
If the current Seraphis library is to store these commitments in their "normal" unmultiplied form while in RAM (like we do now), then yes, mul8 will have to be done on deserialization. However, hypothetically, if we didn't choose to store the commitments like this, then 0 multiplies would have to be done, so we could move over to keeping the commitments in memory mul by 1/8 if the performance losses were worth the review effort, and still remain backwards compatible.

2024-02-26 22:24 UTC, jeffro256 commented
The following snippet of code is how we could hypothetically move to a codebase which does all the above actions without a single multiplication, while still keeping rigidity and not affecting the code structure too much. We would add a class that caches a pubkey and it's 1/8 multiplication, constructing lazily:

```
/**
 * @brief pubcie: PUBkey Cache of Inverse Eight multiplication
 *
 * Lazy, rigid, opaque representation of an Ed25519 point and it multiplied by the inverse of the
 * curve cofactor. Should be stored persistenly in its "fast storage" form, which is it multiplied
 * by 1/8. This is because it is faster to multiply by 8 than 1/8. Monero serialization and Seraphis
 * transcript implementations provided below.
*/
class pubcie
{
public:
    pubcie(): m_cache_status(GIVEN_X) {}

    const rct::key& get() const
    {
        switch (m_cache_status)
        {
        case GIVEN_X:
        case DERIVED_INV8_X:
            return m_given;
        case GIVEN_INV8_X:
            m_derived = rct::scalarmult8(m_given);
            m_cache_status = DERIVED_X;
        case DERIVED_X:
            return m_derived;
        }
    }

    const rct::key& get_mul_inv8() const
    {
        switch (m_cache_status)
        {
        case GIVEN_INV8_X:
        case DERIVED_X:
            return m_given;
        case GIVEN_X:
            m_derived = rct::scalarmultKey(m_given, rct::INV_EIGHT);
            assert(rct::scalarmult8(m_derived) == m_given); // assert m_given can be restored later
            m_cache_status = DERIVED_INV8_X;
        case DERIVED_INV8_X:
            return m_derived;
        }
    }

    const rct::key& get_faststorage_form() const { return get_mul_inv8(); }

    void set(const rct::key &x)
    {
        m_given = x;
        m_cache_status = GIVEN_X;
    }

    void set_mul_inv8(const rct::key &x_mul_inv8)
    {
        m_given = x_mul_inv8;
        m_cache_status = GIVEN_INV8_X;
    }

    void set_faststorage_form(const rct::key &x_storage) { set_mul_inv8(x_storage); }

    BEGIN_SERIALIZE()
        rct::key x_stored;
        if constexpr (W)
            x_stored = v.get_faststorage_form();
        if (!do_serialize(x_stored))
            return false;
        if constexpr (!W)
            v.set_faststorage_form(x_stored);
    END_SERIALIZE()

private:
    enum CacheStatus
    {
        GIVEN_X,
        GIVEN_INV8_X,
        DERIVED_X,
        DERIVED_INV8_X
    };

    rct::key m_given;
    mutable rct::key m_derived;
    mutable CacheStatus m_cache_status;
};
```

Then we would make the enote input image and output commitments this `pubcie` type instead of `rct::key`. We would only need to do a mul8 during scanning when the onetime address is properly recomputed, so only for enotes relevant to the receiver. All the other operations (setting up proofs, taking the TXID, view tag computation) would be multiplication free.

We don't have to do this now, but this could offer us a future path for a clean, backwards-compatible transition to 0 multiplication commitment handling if we decided it's worth the review work.

2024-02-29 15:16 UTC, jeffro256 commented
One note about adding points in 1/8 form to the transcript: if you didn't get the points from a source where you already multiplied by 8 from (i.e. the serialization format), then you need to check that `rct::scalarmult8(one_eighth_P) == P`, since if a developer gives you a point from some other place, the original point might not be in the prime subgroup, and multiplying by 1/8 will not bind that point completely (i.e. the transaction ID would be malleable). There's also rare cases where the `rct::key` can be in a non-canonical format, which would also cause malleability issues.

2024-02-29 18:00 UTC, jeffro256 commented
I went ahead and changed the transcript code so they get added in (1/8) form to demonstrate the approach I'm going for (didn't touch serialization tho). Will revert if not desired

2024-03-05 02:08 UTC, UkoeHB commented
> However, hypothetically, if we didn't choose to store the commitments like this, then 0 multiplies would have to be done, so we could move over to keeping the commitments in memory mul by 1/8 if the performance losses were worth the review effort, and still remain backwards compatible.

The main issue is whenever you actually need to use the commitments, you need to mul8, which is easy to forget and then there are bugs.

> We don't have to do this now, but this could offer us a future path for a clean, backwards-compatible transition to 0 multiplication commitment handling if we decided it's worth the review work.

Hmm this could work. I think this is worthwhile to consider in the future, but right now you should stay focused on progressing toward the wallet implementation. Also note this topic may become obsolete if a different curve is implemented.

2024-03-05 03:51 UTC, UkoeHB commented on src/seraphis_core/sp_core_types.cpp
> +    transcript_inout.append("C_inv8", C_inv8);
For now remove this and it can be evaluated in a separate PR.

2024-03-07 16:46 UTC, jeffro256 commented
Rebased

2024-03-22 14:23 UTC, UkoeHB requested changes

2024-03-22 14:23 UTC, UkoeHB commented on src/seraphis_crypto/sp_legacy_proof_helpers.h
> +* brief: bpp_size_bytes{_lr} - get the size of a BP+ proof in bytes (excluding commitments)
```suggestion
* brief: bpp_size_bytes - get the size of a BP+ proof in bytes (excluding commitments)
```

2024-03-22 14:23 UTC, UkoeHB commented on src/seraphis_main/txtype_squashed_v1.cpp
> +        tx_commitments_ptrs.push_back(&curr_tx_commitments);
This is fragile because if `tx_commitments` reallocates then all the pointers will be invalid. You reserve correctly at the start, but it's dangerous. Add an assert that capacity doesn't change across this loop.

2024-03-22 19:14 UTC, merged