SpTxCoinbaseV1: remove block_reward field
UkoeHB/monero pull request #38
Opened 2024-03-08 13:54 UTC by jeffro256

Not storing/serializing `block_reward` saves us a few bytes on coinbase transactions, and makes it so that you can't initialize a coinbase transaction that has a block reward not matching its output sum.

2024-03-21 15:43 UTC, UkoeHB requested changes

2024-03-21 15:43 UTC, UkoeHB commented on src/seraphis_main/tx_validators.cpp
> +    if (output_amount_sum > std::numeric_limits<rct::xmr_amount>::max())
```suggestion
    // expect the output sum doesn't overflow
    // - the sum should be validated against the expected block reward separately
    if (output_amount_sum > std::numeric_limits<rct::xmr_amount>::max())
```

2024-03-21 15:43 UTC, UkoeHB commented on src/seraphis_mocks/make_mock_tx.cpp
>      MockLedgerContext &ledger_context_inout,
Can you update the calls to `make_mock_tx` for `SpTxCoinbaseV1`?

2024-03-21 17:19 UTC, jeffro256 commented on src/seraphis_mocks/make_mock_tx.cpp
>      MockLedgerContext &ledger_context_inout,
As in remove the arguments from the function signature?

2024-03-21 17:49 UTC, UkoeHB commented on src/seraphis_mocks/make_mock_tx.cpp
>      MockLedgerContext &ledger_context_inout,
Default initialize parameters that are currently writing in amounts that are ignored.

2024-03-22 14:02 UTC, UkoeHB approved these changes
I'll take it lol, thanks

2024-03-22 14:03 UTC, merged